channels:
    - conda-forge
    - defaults
name:
    cloud-ilastik-example
dependencies:
    - pip
    - h5py
    - scikit-image
    - tqdm
    - z5py
    - dask
    - zarr
    - pip:
        - napari[all]
        - dagster
        - dagit
        - structlog
        - colorama
